### ISSUE TITLE
Admin

### ISSUE THREAD

**Issue by concentrateddon** [devops-collective-inc/devops-the-ops-perspective#5]
@ScriptAutomate get James Petty to make you an admin on this repo! I’m actually not anymore, and he has to push the button in LeanPub to re publish the book, too.

**Comment by JamesDBartlett3** [comment]
@ScriptAutomate Are you taking over this repo? I have [a PR that's been open since October](https://github.com/devops-collective-inc/devops-the-ops-perspective/pull/4), and would like to see it merged at some point.

**Comment by psjamesp** [comment]
@JamesDBartlett merged. I’ll push the button in leanpub shortly
